package e

const (
	SUCCESS       = 200
	ERROR         = 500
	INVALID_PARAM = 400

	ERROR_AUTH       = 600
	ERROR_AUTH_TOKEN = 601

	ERROR_AUTH_CHECK_TOKEN_TIMEOUT  = 602
	ERROR_AUTH_CHECK_TOKEN_FAIL     = 603
	ERROR_EXIST_USER                = 604
	ERROR_UPLOAD_CHECK_IMAGE_FORMAT = 605
	ERROR_UPLOAD_PREPARE_IMAGE_FAIL = 606
	ERROR_UPLOAD_SAVE_IMAGE_FAIL    = 607
)
